### ISSUE TITLE
İmport:page   use method  array_merge  1 parametre dizi değil hatası.

### ISSUE THREAD

**Issue by ufk181** [znframework/multi-edition#1]
Internal\IndividualStructures\Import\View.php dizininde bulunan , use methodundaki  $data paremetresi array olarak gönderileceğine NULL olarak gönderilmiş ve method içerisinde override yapılmadığı için array_merge'de hata alıyor. 

$data = NULL yerine $data = [] yaparsanız hata düzeliyor. 

![calisan](https://user-images.githubusercontent.com/26649915/28836625-52fc50f4-76f2-11e7-8389-5410246b0b41.png)

**Comment by ozanuykun** [comment]
Kullanında hata yok NULL olması demek hem array hemde null parametre gönderebilir anlamına gelir. Düzeltimesi gereken bir durum yok. Bu yöntemin kullanıdığı kontrolcüler içerisinde view yönteminin 2. parametresine NULL veya Array dışında parametre gönderimi yapıldığı için bu hatayı alıyorsunuz.
