### ISSUE TITLE
Konsol Tabanlı Çalışma [zerocore] 

### ISSUE THREAD

**Issue by ufk181** [znframework/multi-edition#2]
Konsol ekranında ; 

 php zerocore  create-controller  Controller-name olarak komut gönderdiğimiz de  resimdeki hatayı vermektedir. 

 
![konsol](https://user-images.githubusercontent.com/26649915/32979292-84da1752-cc63-11e7-817d-4b88d1f7f7ea.png)

**Comment by ozanuykun** [comment]
Settings/Projects.php ayar dosyasında yer alan $default ?? 'Frontend' ifadesini $default ?: 'Frontend' olarak düzenleyiniz.

**Comment by diloabininyeri** [comment]
Php 7 ile calisirsan hatta gider ?? Php 7 ile gelen bir ozelik  x ?? Y ?? Z ?? Q  uzayip gider x yoksa y yoksa z yoksa Q alir
